### ISSUE TITLE
pywb returns status code 200 when archive url not found

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/ukwa-pywb#45] opened 2019-08-09 11:00 UTC
For example, https://webarchive.org.uk/wayback/archive/2019/www.coinbase.com
In the wa-www nginx log, this request is recorded as a status code 200 whereas the on-screen message is "Url Not Found
The url http://www.coinbase.com/ could not be found in this collection. ".

**Comment by ikreymer** [comment] 2019-11-01 00:18
The inner frame response, `https://www.webarchive.org.uk/wayback/archive/2019mp_/http://www.coinbase.com/` is a 404, but not the outer frame, which is always a 200.
The reason is that the lookup does not happen until the inner frame is loaded, to avoid a double query and load the outer frame quickly, but maybe there's a way to improve this..

**Comment by anjackson** [comment] 2019-11-06 22:38
Related somewhat to #44. Note that the TimeGate URL (https://beta.webarchive.org.uk/wayback/archive/http://www.coinbase.com/) does the right thing.

**Comment by anjackson** [comment] 2019-11-12 13:57
I'm going to call this ticket a duplicate of #44, having clarified that this is part of that issue.

**Closed by anjackson** 2019-11-12 13:57 UTC
